export const movieData = [
  {
    _id: "65ef3f34675dde8010853667",
    id: 522931,
    title: "Hitman's Wife's Bodyguard",
    vote_average: 6.71,
    vote_count: 1957,
    status: "Released",
    release_date: "2021-06-14T00:00:00.000Z",
    revenue: 70060492,
    runtime: 117,
    adult: false,
    backdrop_path: "/cmquA5exHGsOfcVDrwitAN1EDmN.jpg",
    budget: 70000000,
    homepage: "https://www.thehitmanswifesbodyguard.movie",
    imdb_id: "tt8385148",
    original_language: "en",
    original_title: "Hitman's Wife's Bodyguard",
    overview:
      "The world’s most lethal odd couple – bodyguard Michael Bryce and hitman Darius Kincaid – are back on another life-threatening mission. Still unlicensed and under scrutiny, Bryce is forced into action by Darius's even more volatile wife, the infamous international con artist Sonia Kincaid. As Bryce is driven over the edge by his two most dangerous protectees, the trio get in over their heads in a global plot and soon find that they are all that stand between Europe and a vengeful and powerful madman.",
    popularity: 23.808,
    poster_path:
      "https://image.tmdb.org/t/p/original//6zwGWDpY8Zu0L6W4SYWERBR8Msw.jpg",
    tagline: "Killer threesome.",
    genres: "Action, Comedy, Crime, Thriller",
    production_companies:
      "Nu Boyana Film Studios, Summit Entertainment, Lionsgate, Millennium Media, Davis Films",
    production_countries: "Bulgaria, France, United States of America",
    spoken_languages: "English, Japanese",
  },
  {
    _id: "65ef3f32675dde8010853461",
    id: 406759,
    title: "Moonfall",
    vote_average: 6.355,
    vote_count: 2650,
    status: "Released",
    release_date: "2022-02-03T00:00:00.000Z",
    revenue: 67295363,
    runtime: 131,
    adult: false,
    backdrop_path: "/8QpzqK3nPGxpqpKqhe6QasTGBWQ.jpg",
    budget: 146000000,
    homepage: "https://moonfall.movie",
    imdb_id: "tt5834426",
    original_language: "en",
    original_title: "Moonfall",
    overview:
      "A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.",
    popularity: 55.7,
    poster_path:
      "https://image.tmdb.org/t/p/original//odVv1sqVs0KxBXiA8bhIBlPgalx.jpg",
    tagline: "Humanity will face the dark side of the Moon.",
    genres: "Science Fiction, Adventure, Action",
    production_companies:
      "Centropolis Entertainment, Street Entertainment, Lionsgate, AGC Studios, Huayi Tencent Entertainment Company, Huayi Brothers International",
    production_countries: "Hong Kong, United Kingdom, United States of America",
    spoken_languages: "Mandarin, English, French",
  },
  {
    _id: "65ef3f37675dde8010853ef4",
    id: 522016,
    title: "The 355",
    vote_average: 6.139,
    vote_count: 859,
    status: "Released",
    release_date: "2022-01-05T00:00:00.000Z",
    revenue: 55700000,
    runtime: 122,
    adult: false,
    backdrop_path: "/dEE5tjmrxf4xrKrTnyghLsPSt6f.jpg",
    budget: 75000000,
    homepage: "https://www.the355movie.com",
    imdb_id: "tt8356942",
    original_language: "en",
    original_title: "The 355",
    overview:
      "A group of top female agents from American, British, Chinese, Colombian, and German government agencies are drawn together to try and stop an organization from acquiring a deadly weapon to send the world into chaos.",
    popularity: 29.949,
    poster_path:
      "https://image.tmdb.org/t/p/original//k26FYPVrLRHYnv5ZbMsIHFsjdIM.jpg",
    tagline: "Work together or die alone.",
    genres: "Action, Thriller",
    production_companies:
      "Freckle Films, Genre Films, FilmNation Entertainment, Universal Pictures, Demei Holdings Limited, CNC, Firstep, Episode Films Co., Zak Productions",
    production_countries:
      "France, Hong Kong, Morocco, Taiwan, United States of America",
    spoken_languages: "Arabic, English, French, Mandarin, Spanish, German",
  },
  {
    _id: "65ef3f34675dde8010853781",
    id: 763285,
    title: "Ambulance",
    vote_average: 6.7,
    vote_count: 1714,
    status: "Released",
    release_date: "2022-03-16T00:00:00.000Z",
    revenue: 51783040,
    runtime: 136,
    adult: false,
    backdrop_path: "/rdOIqwR7P7fvTpC6LILSmQxEg6O.jpg",
    budget: 40000000,
    homepage: "https://www.ambulance.movie",
    imdb_id: "tt4998632",
    original_language: "en",
    original_title: "Ambulance",
    overview:
      "Decorated veteran Will Sharp, desperate for money to cover his wife's medical bills, asks for help from his adoptive brother Danny. A charismatic career criminal, Danny instead offers him a score: the biggest bank heist in Los Angeles history: $32 million.",
    popularity: 31.656,
    poster_path:
      "https://image.tmdb.org/t/p/original//kuxjMVuc3VTD7p42TZpJNsSrM1V.jpg",
    tagline: "It was supposed to be a simple heist.",
    genres: "Thriller, Action",
    production_companies:
      "Universal Pictures, Bay Films, Endeavor Content, New Republic Pictures, Project X Entertainment",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f34675dde8010853693",
    id: 619730,
    title: "Don't Worry Darling",
    vote_average: 6.81,
    vote_count: 1911,
    status: "Released",
    release_date: "2022-09-21T00:00:00.000Z",
    revenue: 86669039,
    runtime: 123,
    adult: false,
    backdrop_path: "/3ibGaDmgTdXY448ENZmtHEmhP6o.jpg",
    budget: 35000000,
    homepage: "https://www.dontworrydarling.movie",
    imdb_id: "tt10731256",
    original_language: "en",
    original_title: "Don't Worry Darling",
    overview:
      "Alice and Jack are lucky to be living in the idealized community of Victory, the experimental company town housing the men who work for the top-secret Victory Project and their families. But when cracks in their idyllic life begin to appear, exposing flashes of something much more sinister lurking beneath the attractive façade, Alice can’t help questioning exactly what they’re doing in Victory, and why.",
    popularity: 30.556,
    poster_path:
      "https://image.tmdb.org/t/p/original//wjAJWfuE5OQm5zerlOAbTxdHFMV.jpg",
    tagline: "Are you ready to live the life you deserve?",
    genres: "Thriller, Mystery, Drama",
    production_companies:
      "Vertigo Entertainment, New Line Cinema, Warner Bros. Pictures",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f57675dde80108582ec",
    id: 719256,
    title: "Jesus Revolution",
    vote_average: 6.9,
    vote_count: 75,
    status: "Released",
    release_date: "2023-02-23T00:00:00.000Z",
    revenue: 52300000,
    runtime: 120,
    adult: false,
    backdrop_path: "/m42PtAhEtEqbNV8Cs8TsXcTN4ha.jpg",
    budget: 15000000,
    homepage: "https://jesusrevolution.movie/",
    imdb_id: "tt10098448",
    original_language: "en",
    original_title: "Jesus Revolution",
    overview:
      "In the 1970s, aimless teenager Greg Laurie searches for all the right things in all the wrong places until he meets Lonnie Frisbee, a charismatic hippie/street preacher. Together with local pastor Chuck Smith, they open the doors of a languishing church to an unexpected revival.",
    popularity: 25.539,
    poster_path:
      "https://image.tmdb.org/t/p/original//A3qqrl8lJvlpRCwkbUEADXzVaDC.jpg",
    tagline: "When you open your heart...there's room for everyone.",
    genres: "Drama, History",
    production_companies: "Lionsgate, Kingdom Story Company",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f42675dde8010854d45",
    id: 906221,
    title: "Magic Mike's Last Dance",
    vote_average: 6.8,
    vote_count: 355,
    status: "Released",
    release_date: "2023-02-09T00:00:00.000Z",
    revenue: 52000000,
    runtime: 112,
    adult: false,
    backdrop_path: "/wVxlmhk4OS2eCr0wTQcM4zJ20ml.jpg",
    budget: 45000000,
    homepage: "https://www.magicmikeslastdancemovie.com/",
    imdb_id: "tt16280138",
    original_language: "en",
    original_title: "Magic Mike's Last Dance",
    overview:
      "Mike Lane takes to the stage again after a lengthy hiatus, following a business deal that went bust, leaving him broke and taking bartender gigs in Florida. For what he hopes will be one last hurrah, Mike heads to London with a wealthy socialite who lures him with an offer he can’t refuse… and an agenda all her own. With everything on the line, once Mike discovers what she truly has in mind, will he—and the roster of hot new dancers he’ll have to whip into shape—be able to pull it off?",
    popularity: 27.894,
    poster_path:
      "https://image.tmdb.org/t/p/original//9a9pyJZRhUWUSBT8BQqWihtqbI8.jpg",
    tagline: "The final tease.",
    genres: "Comedy, Drama, Romance",
    production_companies:
      "Warner Bros. Pictures, Nick Wechsler Productions, Free Association",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f42675dde8010854d80",
    id: 592863,
    title: "Respect",
    vote_average: 6.774,
    vote_count: 350,
    status: "Released",
    release_date: "2021-08-12T00:00:00.000Z",
    revenue: 31217372,
    runtime: 145,
    adult: false,
    backdrop_path: "/m0ppE0yXQeFWzlwLdDUFRfanp9R.jpg",
    budget: 0,
    homepage: "https://respect.movie/",
    imdb_id: "tt2452150",
    original_language: "en",
    original_title: "Respect",
    overview:
      "The rise of Aretha Franklin’s career from a child singing in her father’s church’s choir to her international superstardom.",
    popularity: 13.705,
    poster_path:
      "https://image.tmdb.org/t/p/original//iUtPwOBZJc8uJnDqlCXTibdgxKz.jpg",
    tagline: "The queen arrives.",
    genres: "Drama, Music, History",
    production_companies:
      "Metro-Goldwyn-Mayer, Bron Studios, Creative Wealth Media Finance, Cinesite, Glickmania",
    production_countries: "Canada, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f34675dde80108535a4",
    id: 602269,
    title: "The Little Things",
    vote_average: 6.329,
    vote_count: 2158,
    status: "Released",
    release_date: "2021-01-28T00:00:00.000Z",
    revenue: 29942746,
    runtime: 128,
    adult: false,
    backdrop_path: "/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg",
    budget: 30000000,
    homepage: "https://www.thelittlethingsmovie.com",
    imdb_id: "tt10016180",
    original_language: "en",
    original_title: "The Little Things",
    overview:
      "Deputy Sheriff Joe \"Deke\" Deacon joins forces with Sgt. Jim Baxter to search for a serial killer who's terrorizing Los Angeles. As they track the culprit, Baxter is unaware that the investigation is dredging up echoes of Deke's past, uncovering disturbing secrets that could threaten more than his case.",
    popularity: 37.106,
    poster_path:
      "https://image.tmdb.org/t/p/original//tLO1aD1ghdtVMT32z2sRmzgYKYd.jpg",
    tagline: "Some things never let us go.",
    genres: "Crime, Drama, Thriller",
    production_companies: "Warner Bros. Pictures, Gran Via Productions",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f36675dde8010853cf4",
    id: 616651,
    title: "Stillwater",
    vote_average: 6.666,
    vote_count: 1019,
    status: "Released",
    release_date: "2021-07-29T00:00:00.000Z",
    revenue: 19754272,
    runtime: 139,
    adult: false,
    backdrop_path: "/ckCrunvxJ1SqL1w4goJGGGZ5PGP.jpg",
    budget: 20000000,
    homepage: "https://www.focusfeatures.com/stillwater",
    imdb_id: "tt10696896",
    original_language: "en",
    original_title: "Stillwater",
    overview:
      "Bill Baker, an American oil-rig roughneck from Oklahoma, travels to Marseille to visit his estranged daughter, Allison, who is in prison for a murder she claims she did not commit. Confronted with language barriers, cultural differences, and a complicated legal system, Bill builds a new life for himself in France as he makes it his personal mission to exonerate his daughter.",
    popularity: 22.616,
    poster_path:
      "https://image.tmdb.org/t/p/original//cPdmPwcIcmu0ugfKcdFtI3vmOJq.jpg",
    tagline: "Secrets run deep.",
    genres: "Drama, Crime, Thriller",
    production_companies:
      "Anonymous Content, Slow Pony Pictures, DreamWorks Pictures, Participant, Amblin Partners, Focus Features, Firstep, 3dot Productions",
    production_countries: "France, United States of America",
    spoken_languages: "English, French, Spanish",
  },
  {
    _id: "65ef3f44675dde801085535c",
    id: 567690,
    title: "Dear Evan Hansen",
    vote_average: 6.343,
    vote_count: 270,
    status: "Released",
    release_date: "2021-09-24T00:00:00.000Z",
    revenue: 19200000,
    runtime: 137,
    adult: false,
    backdrop_path: "/anl65DJYFyp2m0lXaFvlCrSOT8E.jpg",
    budget: 27500000,
    homepage: "https://www.dehmovie.com",
    imdb_id: "tt9357050",
    original_language: "en",
    original_title: "Dear Evan Hansen",
    overview:
      "Evan Hansen, a high schooler with social anxiety, unintentionally gets caught up in a lie after the family of a classmate who committed suicide mistakes one of Hansen’s letters for their son’s suicide note.",
    popularity: 14.564,
    poster_path:
      "https://image.tmdb.org/t/p/original//hKjBQhsnCMt86kPKpPwV4meeFPo.jpg",
    tagline: "An honest and original story for the outsider in all of us.",
    genres: "Drama",
    production_companies:
      "Universal Pictures, Marc Platt Productions, Perfect World Pictures, dentsu",
    production_countries: "Japan, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f34675dde8010853810",
    id: 559907,
    title: "The Green Knight",
    vote_average: 6.57,
    vote_count: 1605,
    status: "Released",
    release_date: "2021-07-29T00:00:00.000Z",
    revenue: 18888418,
    runtime: 130,
    adult: false,
    backdrop_path: "/kIQc0kkqIYTo65x5XjlKgqdDQ6a.jpg",
    budget: 15000000,
    homepage: "http://thegreenknight.movie",
    imdb_id: "tt9243804",
    original_language: "en",
    original_title: "The Green Knight",
    overview:
      "An epic fantasy adventure based on the timeless Arthurian legend, The Green Knight tells the story of Sir Gawain, King Arthur's reckless and headstrong nephew, who embarks on a daring quest to confront the eponymous Green Knight, a gigantic emerald-skinned stranger and tester of men.",
    popularity: 19.04,
    poster_path:
      "https://image.tmdb.org/t/p/original//if4hw3Ou5Sav9Em7WWHj66mnywp.jpg",
    tagline: "When honor was everything.",
    genres: "Adventure, Drama, Fantasy",
    production_companies:
      "A24, Bron Studios, Sailor Bear, Ley Line Entertainment, Wild Atlantic Pictures, Creative Wealth Media Finance",
    production_countries:
      "Canada, Ireland, United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f34675dde80108538de",
    id: 716612,
    title: "Spencer",
    vote_average: 6.858,
    vote_count: 1475,
    status: "Released",
    release_date: "2021-11-04T00:00:00.000Z",
    revenue: 14000000,
    runtime: 117,
    adult: false,
    backdrop_path: "/uAf1Ua3UDm8cDR2CgNGbZepOqDV.jpg",
    budget: 18000000,
    homepage: "https://neonrated.com/films/spencer",
    imdb_id: "tt12536294",
    original_language: "en",
    original_title: "Spencer",
    overview:
      "During her Christmas holidays with the royal family at the Sandringham estate in Norfolk, England, Diana decides to leave her marriage to Prince Charles.",
    popularity: 13.478,
    poster_path:
      "https://image.tmdb.org/t/p/original//7GcqdBKaMM9BWXWN07BirBMkcBF.jpg",
    tagline: "Every fairy tale ends.",
    genres: "Drama",
    production_companies:
      "FilmNation Entertainment, Komplizen Film, Shoebox Films, Fabula, Fabula",
    production_countries:
      "Chile, Germany, United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f3d675dde8010854b53",
    id: 814757,
    title: "Empire of Light",
    vote_average: 6.7,
    vote_count: 392,
    status: "Released",
    release_date: "2022-12-09T00:00:00.000Z",
    revenue: 11320643,
    runtime: 115,
    adult: false,
    backdrop_path: "/bFAozpBc5s0cJcolKABpa5THusM.jpg",
    budget: 0,
    homepage: "https://www.empirelightfilm.com",
    imdb_id: "tt14402146",
    original_language: "en",
    original_title: "Empire of Light",
    overview:
      "The duty manager of a seaside cinema, who is struggling with her mental health, forms a relationship with a new employee on the south coast of England in the 1980s.",
    popularity: 14.8,
    poster_path:
      "https://image.tmdb.org/t/p/original//h84SnIQF91Gz2Fv1OpMJ3245t4i.jpg",
    genres: "Drama, Romance",
    production_companies:
      "Searchlight Pictures, Neal Street Productions, TSG Entertainment",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f39675dde8010854510",
    id: 596161,
    title: "Let Him Go",
    vote_average: 6.833,
    vote_count: 559,
    status: "Released",
    release_date: "2020-11-05T00:00:00.000Z",
    revenue: 7997460,
    runtime: 114,
    adult: false,
    backdrop_path: "/ZLD4pjmMLt9I3t1a7SFJBekIh1.jpg",
    budget: 21000000,
    homepage: "https://www.focusfeatures.com/let-him-go",
    imdb_id: "tt9340860",
    original_language: "en",
    original_title: "Let Him Go",
    overview:
      "Following the loss of their son, a retired sheriff and his wife leave their Montana ranch to rescue their young grandson from the clutches of a dangerous family living off the grid in the Dakotas.",
    popularity: 14.235,
    poster_path:
      "https://image.tmdb.org/t/p/original//EsLZoT8oHhQlGd1QpdbnvnwTzO.jpg",
    tagline: "Fight for family.",
    genres: "Drama, Thriller, Crime, Western",
    production_companies: "Mazur / Kaplan Company, Focus Features",
    production_countries: "Canada, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f42675dde8010854f1a",
    id: 615952,
    title: "Armageddon Time",
    vote_average: 6.58,
    vote_count: 325,
    status: "Released",
    release_date: "2022-10-28T00:00:00.000Z",
    revenue: 6100000,
    runtime: 114,
    adult: false,
    backdrop_path: "/giveZjQGE4Pn3kJvsTn7uHqLjZS.jpg",
    budget: 15000000,
    homepage: "https://www.focusfeatures.com/armageddon-time",
    imdb_id: "tt10343028",
    original_language: "en",
    original_title: "Armageddon Time",
    overview:
      "In 1980, Queens, New York, a young Jewish boy befriends a rebellious African-American classmate to the disapproval of his privileged family and begins to reckon with growing up in a world of inequality and prejudice.",
    popularity: 14.695,
    poster_path:
      "https://image.tmdb.org/t/p/original//d0fkTMTN91f0tehqVKG9D9JMsDR.jpg",
    tagline: "The end of an era. The beginning of everything.",
    genres: "Drama",
    production_companies:
      "RT Features, Spacemaker Productions, Keep Your Head Productions, MadRiver Pictures, Focus Features",
    production_countries: "Brazil, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f37675dde8010853fb5",
    id: 643532,
    title: "The Card Counter",
    vote_average: 6.173,
    vote_count: 810,
    status: "Released",
    release_date: "2021-09-03T00:00:00.000Z",
    revenue: 5040860,
    runtime: 111,
    adult: false,
    backdrop_path: "/5q1bHsA7Xff39CH2PHHFpRXYNrs.jpg",
    budget: 0,
    homepage: "https://www.focusfeatures.com/the-card-counter",
    imdb_id: "tt11196036",
    original_language: "en",
    original_title: "The Card Counter",
    overview:
      "William Tell just wants to play cards. His spartan existence on the casino trail is shattered when he is approached by Cirk, a vulnerable and angry young man seeking help to execute his plan for revenge on a military colonel. Tell sees a chance at redemption through his relationship with Cirk. But keeping Cirk on the straight-and-narrow proves impossible, dragging Tell back into the darkness of his past.",
    popularity: 14.852,
    poster_path:
      "https://image.tmdb.org/t/p/original//y5DNLVg0gPiGSkuK4yFc4fjQ42Q.jpg",
    tagline: "He's Playing the Hand He Was Dealt.",
    genres: "Drama, Thriller",
    production_companies:
      "Focus Features, LB Entertainment, Astrakan Films AB, Convergent Media, Enriched Media Group, HanWay Films, One Two Twenty Entertainment, Redline Entertainment",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f5e675dde80108591fe",
    id: 659994,
    title: "Rams",
    vote_average: 6.143,
    vote_count: 57,
    status: "Released",
    release_date: "2020-10-15T00:00:00.000Z",
    revenue: 4155492,
    runtime: 119,
    adult: false,
    backdrop_path: "/iwiG2Dx16AnnqiJE2BMJCJkaScA.jpg",
    budget: 0,
    homepage: "https://roadshow.com.au/titles/movies/roadshow/2020/rams",
    imdb_id: "tt8737608",
    original_language: "en",
    original_title: "Rams",
    overview:
      "In remote Western Australia, two estranged farmer brothers, Colin and Les, are at war. But when Les' prize ram is diagnosed with a rare and lethal illness, authorities order a purge of every sheep in the valley—so the brothers must work together to reunite their family, save their herd, and bring their community back together.",
    popularity: 6.031,
    poster_path:
      "https://image.tmdb.org/t/p/original//6YPtbdNnZQAnBL0sBA0AKNykdIT.jpg",
    tagline: "Where there's a wool, there's a way",
    genres: "Drama, Comedy",
    production_companies: "Village Roadshow Entertainment, WBMC",
    production_countries: "Australia",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f39675dde80108543b1",
    id: 424277,
    title: "Annette",
    vote_average: 6.765,
    vote_count: 608,
    status: "Released",
    release_date: "2021-07-06T00:00:00.000Z",
    revenue: 3642692,
    runtime: 140,
    adult: false,
    backdrop_path: "/cDVWsqsnGwIUqOSzAuDS0PIhNdW.jpg",
    budget: 15500000,
    homepage: "https://www.amazon.com/dp/B093KHDSHR",
    imdb_id: "tt6217926",
    original_language: "en",
    original_title: "Annette",
    overview:
      "The story of Henry, a stand-up comedian with a fierce sense of humour and Ann, a singer of international renown. In the spotlight, they are the perfect couple, healthy, happy, and glamourous. The birth of their first child, Annette, a mysterious girl with an exceptional destiny, will change their lives.",
    popularity: 10.471,
    poster_path:
      "https://image.tmdb.org/t/p/original//4FTnypxpGltJdIARrfFsP31pGTp.jpg",
    tagline: "As dangerous, as intense, as love.",
    genres: "Drama, Romance",
    production_companies:
      "Eurospace, Detailfilm, ARTE France Cinéma, CG Cinéma, Garidi Films, Théo Films, Tribus P Films, UGC, SCOPE Pictures, Wrong Men, Piano",
    production_countries:
      "Belgium, Canada, France, Germany, Greece, Japan, Mexico, Switzerland",
    spoken_languages: "English, French",
  },
  {
    _id: "65ef3f44675dde8010855267",
    id: 806368,
    title: "The Son",
    vote_average: 6.673,
    vote_count: 281,
    status: "Released",
    release_date: "2022-11-10T00:00:00.000Z",
    revenue: 3564844,
    runtime: 123,
    adult: false,
    backdrop_path: "/5iMLD2KE0JQcPchegqSpKstU4CT.jpg",
    budget: 0,
    homepage: "https://tickets.theson-film.com",
    imdb_id: "tt14458442",
    original_language: "en",
    original_title: "The Son",
    overview:
      "A successful lawyer, with a new wife and infant, agrees to care for his teenage son from a previous marriage after his ex-wife becomes concerned about the boy's wayward behavior.",
    popularity: 18.957,
    poster_path:
      "https://image.tmdb.org/t/p/original//hYR2doH3arnX0Y6WULuBPbtaLjN.jpg",
    genres: "Drama",
    production_companies:
      "Film4 Productions, Ingenious Media, Embankment Films, See-Saw Films, Cross City Films, Inthevoid Production, Sony Pictures Classics, STX Films",
    production_countries: "France, United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f37675dde80108540f5",
    id: 480857,
    title: "Radioactive",
    vote_average: 6.611,
    vote_count: 734,
    status: "Released",
    release_date: "2020-03-11T00:00:00.000Z",
    revenue: 3507755,
    runtime: 111,
    adult: false,
    backdrop_path: "/iFFC0ILEzcCGI8fJzixI9lI5n8o.jpg",
    budget: 0,
    homepage: "https://www.workingtitlefilms.com/film/radioactive/",
    imdb_id: "tt6017756",
    original_language: "en",
    original_title: "Radioactive",
    overview:
      "The story of Nobel Prize winner Marie Curie and her extraordinary scientific discoveries—through the prism of her marriage to husband Pierre—and the seismic and transformative effects their discovery of radium had on the 20th century.",
    popularity: 10.153,
    poster_path:
      "https://image.tmdb.org/t/p/original//akHIQu8W3rOgT28r25ggXaKcQIr.jpg",
    tagline: "Pioneer. Genius. Rebel.",
    genres: "Drama, Romance, History",
    production_companies:
      "Working Title Films, StudioCanal, Shoebox Films, Pioneer Stilking Films, Canal+",
    production_countries: "France, United Kingdom",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f45675dde8010855550",
    id: 730047,
    title: "Cyrano",
    vote_average: 6.436,
    vote_count: 251,
    status: "Released",
    release_date: "2021-12-17T00:00:00.000Z",
    revenue: 3000000,
    runtime: 124,
    adult: false,
    backdrop_path: "/cfDQh8STZvzXtyr1iyb4cXzkLju.jpg",
    budget: 20000000,
    homepage: "https://www.unitedartistsreleasing.com/cyrano/synopsis/",
    imdb_id: "tt12889404",
    original_language: "en",
    original_title: "Cyrano",
    overview:
      "A man ahead of his time, Cyrano de Bergerac dazzles whether with ferocious wordplay at a verbal joust or with brilliant swordplay in a duel. But, convinced that his appearance renders him unworthy of the love of a devoted friend, the luminous Roxanne, Cyrano has yet to declare his feelings for her—and Roxanne has fallen in love, at first sight, with Christian.",
    popularity: 11.365,
    poster_path:
      "https://image.tmdb.org/t/p/original//e4koV8iC2cCM57bqUnEnIL2a2zH.jpg",
    tagline: "Have you ever loved someone?",
    genres: "Drama, Romance",
    production_companies:
      "Metro-Goldwyn-Mayer, Working Title Films, Bron Studios, Creative Wealth Media Finance",
    production_countries: "Canada, United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f3b675dde801085469a",
    id: 601470,
    title: "The Eyes of Tammy Faye",
    vote_average: 6.591,
    vote_count: 508,
    status: "Released",
    release_date: "2021-09-17T00:00:00.000Z",
    revenue: 2404127,
    runtime: 126,
    adult: false,
    backdrop_path: "/rskVKmBb83u7qbaASCxyJyLevkq.jpg",
    budget: 0,
    homepage: "https://www.searchlightpictures.com/theeyesoftammyfaye/",
    imdb_id: "tt9115530",
    original_language: "en",
    original_title: "The Eyes of Tammy Faye",
    overview:
      "From the 1960's to the 1980's, evangelist Jim Baker and his ambitious wife, Tammy Faye, rose from humble beginnings to to build an empire based on big-time evangelical Christianity--only for the couple to fall from grace because of some all-too-human sins.",
    popularity: 14.704,
    poster_path:
      "https://image.tmdb.org/t/p/original//vw5WXyHqAfnhmGpSjpyZh34xau3.jpg",
    tagline: "Sometimes in life, you have to take your lashes.",
    genres: "Drama, History",
    production_companies:
      "Freckle Films, MWM Studios, Searchlight Pictures, Semi-Formal Productions",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f42675dde8010854efc",
    id: 763329,
    title: "Red Rocket",
    vote_average: 6.706,
    vote_count: 326,
    status: "Released",
    release_date: "2021-12-10T00:00:00.000Z",
    revenue: 2200000,
    runtime: 130,
    adult: false,
    backdrop_path: "/gsJQcNtnZEzfkJVi1S8bdzLR4LX.jpg",
    budget: 1100000,
    homepage: "http://redrocket.movie",
    imdb_id: "tt13453006",
    original_language: "en",
    original_title: "Red Rocket",
    overview:
      "Finding himself down and out in Los Angeles, ex porn star Mikey Saber decides to crawl back to his hometown of Texas City, Texas, where his estranged wife and mother-in-law are living. Just as this dysfunctional family seems to be making things work, Mikey meets a young woman named Strawberry working the cash register at a local doughnut shop.",
    popularity: 7.197,
    poster_path:
      "https://image.tmdb.org/t/p/original//345gLhiNpItU1ICx8OxJQwjgPmH.jpg",
    genres: "Drama",
    production_companies: "FilmNation Entertainment, Cre Film",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f37675dde8010853e13",
    id: 531876,
    title: "The Outpost",
    vote_average: 6.885,
    vote_count: 924,
    status: "Released",
    release_date: "2020-06-24T00:00:00.000Z",
    revenue: 2133452,
    runtime: 123,
    adult: false,
    backdrop_path: "/n1RohH2VoK1CdVI2fXvcP19dSlm.jpg",
    budget: 18000000,
    homepage:
      "https://screenmediafilms.net/productions/details/3168/The-Outpost",
    imdb_id: "tt3833480",
    original_language: "en",
    original_title: "The Outpost",
    overview:
      "A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.",
    popularity: 22.097,
    poster_path:
      "https://image.tmdb.org/t/p/original//hPkqY2EMqWUnFEoedukilIUieVG.jpg",
    tagline: "The mission was survival.",
    genres: "War, Drama, History, Action",
    production_companies:
      "Millennium Media, York Films, Perfection Hunter Productions",
    production_countries: "Bulgaria, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f34675dde8010853745",
    id: 796499,
    title: "Army of Thieves",
    vote_average: 6.867,
    vote_count: 1756,
    status: "Released",
    release_date: "2021-10-27T00:00:00.000Z",
    revenue: 46900000,
    runtime: 127,
    adult: false,
    backdrop_path: "/mu8RKavbv7Ml48twHQ6XVk7zw8e.jpg",
    budget: 30000000,
    homepage: "https://www.netflix.com/title/81185548",
    imdb_id: "tt13024674",
    original_language: "en",
    original_title: "Army of Thieves",
    overview:
      "A mysterious woman recruits bank teller Ludwig Dieter to lead a group of aspiring thieves on a top-secret heist during the early stages of the zombie apocalypse.",
    popularity: 22.46,
    poster_path:
      "https://image.tmdb.org/t/p/original//iPTZGFmPs7HsXHYxiuxGolihjOH.jpg",
    tagline: "BEFORE VEGAS, ONE LOCKSMITH BECAME A LEGEND.",
    genres: "Action, Thriller, Crime, Comedy",
    production_companies: "Pantaleon Films, The Stone Quarry, Film United",
    production_countries: "Germany, United States of America",
    spoken_languages: "German, English, Czech, Georgian, French",
  },
  {
    _id: "65ef3f30675dde8010853140",
    id: 338762,
    title: "Bloodshot",
    vote_average: 6.76,
    vote_count: 4681,
    status: "Released",
    release_date: "2020-03-05T00:00:00.000Z",
    revenue: 39861118,
    runtime: 110,
    adult: false,
    backdrop_path: "/lP5eKh8WOcPysfELrUpGhHJGZEH.jpg",
    budget: 42000000,
    homepage: "https://www.bloodshot.movie/",
    imdb_id: "tt1634106",
    original_language: "en",
    original_title: "Bloodshot",
    overview:
      "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
    popularity: 29.852,
    poster_path:
      "https://image.tmdb.org/t/p/original//8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg",
    tagline: "Being a superhero is in his blood",
    genres: "Action, Science Fiction, Adventure",
    production_companies:
      "Cross Creek Pictures, Mimran Schur Pictures, Original Film, The Hideaway Entertainment, Valiant Entertainment, Columbia Pictures, One Race, Bona Film Group, Mid Atlantic Films",
    production_countries:
      "Canada, China, Hungary, South Africa, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f34675dde801085396a",
    id: 568620,
    title: "Snake Eyes: G.I. Joe Origins",
    vote_average: 6.538,
    vote_count: 1397,
    status: "Released",
    release_date: "2021-07-22T00:00:00.000Z",
    revenue: 36964325,
    runtime: 121,
    adult: false,
    backdrop_path: "/2OFg5p9yarI5zZsUWKCRgBgPctj.jpg",
    budget: 88000000,
    homepage: "https://www.snakeeyesmovie.com",
    imdb_id: "tt8404256",
    original_language: "en",
    original_title: "Snake Eyes: G.I. Joe Origins",
    overview:
      "After saving the life of their heir apparent, tenacious loner Snake Eyes is welcomed into an ancient Japanese clan called the Arashikage where he is taught the ways of the ninja warrior. But, when secrets from his past are revealed, Snake Eyes' honor and allegiance will be tested – even if that means losing the trust of those closest to him.",
    popularity: 46.458,
    poster_path:
      "https://image.tmdb.org/t/p/original//uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg",
    tagline: "Every warrior has a beginning.",
    genres: "Action, Adventure",
    production_companies:
      "Paramount, Metro-Goldwyn-Mayer, di Bonaventura Pictures, Entertainment One, Skydance, Hasbro",
    production_countries: "Canada, Japan, United States of America",
    spoken_languages: "English, Arabic, Italian, Japanese",
  },
  {
    _id: "65ef3f36675dde8010853a3c",
    id: 818397,
    title: "Memory",
    vote_average: 6.883,
    vote_count: 1293,
    status: "Released",
    release_date: "2022-04-28T00:00:00.000Z",
    revenue: 13897255,
    runtime: 114,
    adult: false,
    backdrop_path: "/9zXPnbVpaDfTniLBuc5vgXGfzAP.jpg",
    budget: 30000000,
    homepage: "https://www.memorymov.com/",
    imdb_id: "tt11827628",
    original_language: "en",
    original_title: "Memory",
    overview:
      "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
    popularity: 56.091,
    poster_path:
      "https://image.tmdb.org/t/p/original//4Q1n3TwieoULnuaztu9aFjqHDTI.jpg",
    tagline: "His mind is fading. His conscience is clear.",
    genres: "Action, Thriller, Crime",
    production_companies:
      "Black Bear Pictures, Welle Entertainment, Saville Productions, Open Road Films, Briarcliff Entertainment, STX Films",
    production_countries: "United States of America",
    spoken_languages: "Spanish, English",
  },
  {
    _id: "65ef3f37675dde8010853fc9",
    id: 630004,
    title: "The Vault",
    vote_average: 6.843,
    vote_count: 806,
    status: "Released",
    release_date: "2021-03-04T00:00:00.000Z",
    revenue: 8804000,
    runtime: 118,
    adult: false,
    backdrop_path: "/eBGKU0ZLJmxtVtzESTB1mfllX1J.jpg",
    budget: 15000000,
    imdb_id: "tt9742794",
    original_language: "en",
    original_title: "The Vault",
    overview:
      "When an engineer learns of a mysterious, impenetrable fortress hidden under The Bank of Spain, he joins a crew of master thieves who plan to steal the legendary lost treasure locked inside while the whole country is distracted by Spain's World Cup Final. With thousands of soccer fans cheering in the streets, and security forces closing in, the crew have just minutes to pull off the score of a lifetime.",
    popularity: 24.754,
    poster_path:
      "https://image.tmdb.org/t/p/original//kWhXubAiIcHW0xn5GThflqaKZqh.jpg",
    tagline: "No job is impossible.",
    genres: "Action",
    production_companies:
      "Ciudadano Ciskul, El Tesoro de Drake AIE, Telecinco Cinema, Think Studio, Saban Films",
    production_countries: "Spain",
    spoken_languages: "English, Spanish",
  },
  {
    _id: "65ef3f37675dde8010853f44",
    id: 615904,
    title: "Marry Me",
    vote_average: 6.782,
    vote_count: 836,
    status: "Released",
    release_date: "2022-02-09T00:00:00.000Z",
    revenue: 44000000,
    runtime: 112,
    adult: false,
    backdrop_path: "/mJQf866IDnWw7ZkFEM2Oz7QfhW0.jpg",
    budget: 23000000,
    homepage: "https://www.marryme.movie/",
    imdb_id: "tt10223460",
    original_language: "en",
    original_title: "Marry Me",
    overview:
      "Music superstars Kat Valdez and Bastian are getting married before a global audience of fans. But when Kat learns, seconds before her vows, that Bastian has been unfaithful, she decides to marry Charlie, a stranger in the crowd, instead.",
    popularity: 21.375,
    poster_path:
      "https://image.tmdb.org/t/p/original//ko1JVbGj4bT8IhCWqjBQ6ZtF2t.jpg",
    tagline: "Say yes.",
    genres: "Romance, Comedy, Music",
    production_companies:
      "Universal Pictures, Nuyorican Productions, Perfect World Pictures",
    production_countries: "China, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f3d675dde8010854acf",
    id: 614939,
    title: "Bros",
    vote_average: 6.89,
    vote_count: 403,
    status: "Released",
    release_date: "2022-09-30T00:00:00.000Z",
    revenue: 14800000,
    runtime: 115,
    adult: false,
    backdrop_path: "/mezKuuKtAKPENnAVlT3TghkMACv.jpg",
    budget: 22000000,
    homepage: "https://www.brosthemovie.com",
    imdb_id: "tt9731598",
    original_language: "en",
    original_title: "Bros",
    overview: "Two emotionally unavailable men attempt a relationship.",
    popularity: 14.485,
    poster_path:
      "https://image.tmdb.org/t/p/original//op02Hv5i4Z049nGJYmk6BScRqHO.jpg",
    tagline: "A romantic comedy that gives you all the feels.",
    genres: "Comedy, Romance",
    production_companies:
      "Universal Pictures, Apatow Productions, Stoller Global Solutions",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f3d675dde8010854b53",
    id: 814757,
    title: "Empire of Light",
    vote_average: 6.7,
    vote_count: 392,
    status: "Released",
    release_date: "2022-12-09T00:00:00.000Z",
    revenue: 11320643,
    runtime: 115,
    adult: false,
    backdrop_path: "/bFAozpBc5s0cJcolKABpa5THusM.jpg",
    budget: 0,
    homepage: "https://www.empirelightfilm.com",
    imdb_id: "tt14402146",
    original_language: "en",
    original_title: "Empire of Light",
    overview:
      "The duty manager of a seaside cinema, who is struggling with her mental health, forms a relationship with a new employee on the south coast of England in the 1980s.",
    popularity: 14.8,
    poster_path:
      "https://image.tmdb.org/t/p/original//h84SnIQF91Gz2Fv1OpMJ3245t4i.jpg",
    genres: "Drama, Romance",
    production_companies:
      "Searchlight Pictures, Neal Street Productions, TSG Entertainment",
    production_countries: "United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f39675dde80108543b1",
    id: 424277,
    title: "Annette",
    vote_average: 6.765,
    vote_count: 608,
    status: "Released",
    release_date: "2021-07-06T00:00:00.000Z",
    revenue: 3642692,
    runtime: 140,
    adult: false,
    backdrop_path: "/cDVWsqsnGwIUqOSzAuDS0PIhNdW.jpg",
    budget: 15500000,
    homepage: "https://www.amazon.com/dp/B093KHDSHR",
    imdb_id: "tt6217926",
    original_language: "en",
    original_title: "Annette",
    overview:
      "The story of Henry, a stand-up comedian with a fierce sense of humour and Ann, a singer of international renown. In the spotlight, they are the perfect couple, healthy, happy, and glamourous. The birth of their first child, Annette, a mysterious girl with an exceptional destiny, will change their lives.",
    popularity: 10.471,
    poster_path:
      "https://image.tmdb.org/t/p/original//4FTnypxpGltJdIARrfFsP31pGTp.jpg",
    tagline: "As dangerous, as intense, as love.",
    genres: "Drama, Romance",
    production_companies:
      "Eurospace, Detailfilm, ARTE France Cinéma, CG Cinéma, Garidi Films, Théo Films, Tribus P Films, UGC, SCOPE Pictures, Wrong Men, Piano",
    production_countries:
      "Belgium, Canada, France, Germany, Greece, Japan, Mexico, Switzerland",
    spoken_languages: "English, French",
  },
  {
    _id: "65ef3f37675dde80108540f5",
    id: 480857,
    title: "Radioactive",
    vote_average: 6.611,
    vote_count: 734,
    status: "Released",
    release_date: "2020-03-11T00:00:00.000Z",
    revenue: 3507755,
    runtime: 111,
    adult: false,
    backdrop_path: "/iFFC0ILEzcCGI8fJzixI9lI5n8o.jpg",
    budget: 0,
    homepage: "https://www.workingtitlefilms.com/film/radioactive/",
    imdb_id: "tt6017756",
    original_language: "en",
    original_title: "Radioactive",
    overview:
      "The story of Nobel Prize winner Marie Curie and her extraordinary scientific discoveries—through the prism of her marriage to husband Pierre—and the seismic and transformative effects their discovery of radium had on the 20th century.",
    popularity: 10.153,
    poster_path:
      "https://image.tmdb.org/t/p/original//akHIQu8W3rOgT28r25ggXaKcQIr.jpg",
    tagline: "Pioneer. Genius. Rebel.",
    genres: "Drama, Romance, History",
    production_companies:
      "Working Title Films, StudioCanal, Shoebox Films, Pioneer Stilking Films, Canal+",
    production_countries: "France, United Kingdom",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f45675dde8010855550",
    id: 730047,
    title: "Cyrano",
    vote_average: 6.436,
    vote_count: 251,
    status: "Released",
    release_date: "2021-12-17T00:00:00.000Z",
    revenue: 3000000,
    runtime: 124,
    adult: false,
    backdrop_path: "/cfDQh8STZvzXtyr1iyb4cXzkLju.jpg",
    budget: 20000000,
    homepage: "https://www.unitedartistsreleasing.com/cyrano/synopsis/",
    imdb_id: "tt12889404",
    original_language: "en",
    original_title: "Cyrano",
    overview:
      "A man ahead of his time, Cyrano de Bergerac dazzles whether with ferocious wordplay at a verbal joust or with brilliant swordplay in a duel. But, convinced that his appearance renders him unworthy of the love of a devoted friend, the luminous Roxanne, Cyrano has yet to declare his feelings for her—and Roxanne has fallen in love, at first sight, with Christian.",
    popularity: 11.365,
    poster_path:
      "https://image.tmdb.org/t/p/original//e4koV8iC2cCM57bqUnEnIL2a2zH.jpg",
    tagline: "Have you ever loved someone?",
    genres: "Drama, Romance",
    production_companies:
      "Metro-Goldwyn-Mayer, Working Title Films, Bron Studios, Creative Wealth Media Finance",
    production_countries: "Canada, United Kingdom, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f34675dde801085363c",
    id: 619778,
    title: "Malignant",
    vote_average: 6.832,
    vote_count: 2000,
    status: "Released",
    release_date: "2021-09-01T00:00:00.000Z",
    revenue: 34891791,
    runtime: 111,
    adult: false,
    backdrop_path: "/xDnFlNrNUoSKPq4uptnhYmUZNpm.jpg",
    budget: 40000000,
    homepage: "https://www.malignantmovie.net/",
    imdb_id: "tt3811906",
    original_language: "en",
    original_title: "Malignant",
    overview:
      "Madison is paralyzed by shocking visions of grisly murders, and her torment worsens as she discovers that these waking dreams are in fact terrifying realities with a mysterious tie to her past.",
    popularity: 32.356,
    poster_path:
      "https://image.tmdb.org/t/p/original//dGv2BWjzwAz6LB8a8JeRIZL8hSz.jpg",
    tagline: "A new vision of terror.",
    genres: "Horror, Mystery, Thriller",
    production_companies:
      "New Line Cinema, Atomic Monster, Starlight Media, My Entertainment",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f34675dde8010853972",
    id: 663712,
    title: "Terrifier 2",
    vote_average: 6.832,
    vote_count: 1393,
    status: "Released",
    release_date: "2022-10-06T00:00:00.000Z",
    revenue: 15065239,
    runtime: 138,
    adult: false,
    backdrop_path: "/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg",
    budget: 250000,
    homepage: "http://www.terrifier2themovie.com/",
    imdb_id: "tt10403420",
    original_language: "en",
    original_title: "Terrifier 2",
    overview:
      "After being resurrected by a sinister entity, Art the Clown returns to Miles County where he must hunt down and destroy a teenage girl and her younger brother on Halloween night.  As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
    popularity: 84.833,
    poster_path:
      "https://image.tmdb.org/t/p/original//8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg",
    tagline: "Who's laughing now?",
    genres: "Horror, Thriller",
    production_companies:
      "Dark Age Cinema, Fuzz on the Lens Productions, Bloody Disgusting",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f39675dde8010854295",
    id: 516632,
    title: "The Empty Man",
    vote_average: 6.162,
    vote_count: 650,
    status: "Released",
    release_date: "2020-10-22T00:00:00.000Z",
    revenue: 4796993,
    runtime: 137,
    adult: false,
    backdrop_path: "/hwpbTeZEaKKUfiUjc2FJZpv7uAI.jpg",
    budget: 16000000,
    homepage: "https://www.20thcenturystudios.com/movies/the-empty-man",
    imdb_id: "tt5867314",
    original_language: "en",
    original_title: "The Empty Man",
    overview:
      'Retired cop James Lasombra is asked by a friend to investigate the disappearance of her daughter, who seemingly packed in the night and left an ominous message on the bathroom mirror - "The Empty Man Made Me Do It." As he investigates this mysterious figure further, James begins to see and hear strange things, and is forced to come to terms with his past and what it means for his future.',
    popularity: 28.287,
    poster_path:
      "https://image.tmdb.org/t/p/original//8apzu9JFTUMtOpYkHk6LNPOs3pY.jpg",
    tagline:
      "The first night you hear him. The second night you see him. The third night he finds you.",
    genres: "Horror, Mystery, Thriller",
    production_companies:
      "BOOM! Studios, Out of Africa Entertainment, 20th Century Fox",
    production_countries: "South Africa, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f47675dde8010855aec",
    id: 630392,
    title: "The Cursed",
    vote_average: 6.751,
    vote_count: 205,
    status: "Released",
    release_date: "2021-07-28T00:00:00.000Z",
    revenue: 4588389,
    runtime: 111,
    adult: false,
    backdrop_path: "/gRTYArznK1MLAq7opC1tYHnTwM3.jpg",
    budget: 0,
    imdb_id: "tt9907782",
    original_language: "en",
    original_title: "The Cursed",
    overview:
      "In the late 19th century, a brutal land baron slaughters a Roma clan, unleashing a curse on his family and village. In the days that follow, the townspeople are plagued by nightmares, the baron's son goes missing, and a boy is found murdered. The locals suspect a wild animal, but a visiting pathologist warns of a more sinister presence lurking in the woods.",
    popularity: 13.611,
    poster_path:
      "https://image.tmdb.org/t/p/original//bewmBcjJxHeipS1PNu9Lfyvt3zY.jpg",
    genres: "Horror, Fantasy, Mystery",
    production_companies: "Piste Rouge, LD Entertainment",
    production_countries: "United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f37675dde8010853e13",
    id: 531876,
    title: "The Outpost",
    vote_average: 6.885,
    vote_count: 924,
    status: "Released",
    release_date: "2020-06-24T00:00:00.000Z",
    revenue: 2133452,
    runtime: 123,
    adult: false,
    backdrop_path: "/n1RohH2VoK1CdVI2fXvcP19dSlm.jpg",
    budget: 18000000,
    homepage:
      "https://screenmediafilms.net/productions/details/3168/The-Outpost",
    imdb_id: "tt3833480",
    original_language: "en",
    original_title: "The Outpost",
    overview:
      "A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.",
    popularity: 22.097,
    poster_path:
      "https://image.tmdb.org/t/p/original//hPkqY2EMqWUnFEoedukilIUieVG.jpg",
    tagline: "The mission was survival.",
    genres: "War, Drama, History, Action",
    production_companies:
      "Millennium Media, York Films, Perfection Hunter Productions",
    production_countries: "Bulgaria, United States of America",
    spoken_languages: "English",
  },
  {
    _id: "65ef3f37675dde8010853eea",
    id: 574060,
    title: "Gunpowder Milkshake",
    vote_average: 6.375,
    vote_count: 862,
    status: "Released",
    release_date: "2021-07-14T00:00:00.000Z",
    revenue: 1015760,
    runtime: 114,
    adult: false,
    backdrop_path: "/bOYso1vEWhcus8P97lTj2Vw1wkB.jpg",
    budget: 30000000,
    imdb_id: "tt8368408",
    original_language: "en",
    original_title: "Gunpowder Milkshake",
    overview:
      "To protect an 8-year-old girl, a dangerous assassin reunites with her mother and her lethal associates to take down a ruthless crime syndicate and its army of henchmen.",
    popularity: 22.403,
    poster_path:
      "https://image.tmdb.org/t/p/original//5AaKulwpUtkscAokKWtLenGTfVS.jpg",
    tagline: "Revenge is best served ice cold.",
    genres: "Action, Crime, Thriller",
    production_companies:
      "Studio Babelsberg, Canal+, Ciné+, The Picture Company, STX Films, StudioCanal",
    production_countries: "France, Germany, United States of America",
    spoken_languages: "English, Russian",
  },
];
